# Generated by Django 5.2.8 on 2025-11-30 03:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=45, validators=[django.core.validators.validate_ipv46_address])),
                ('location', models.CharField(max_length=32)),
                ('api_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('unhealthy', 'Unhealthy'), ('decommissioned', 'Decommissioned')], default='provisioning', max_length=20)),
                ('cpu_cores', models.PositiveIntegerField()),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('cpu_over_allocation', models.FloatField(default=1.0)),
                ('memory', models.PositiveIntegerField(help_text='Memory in MB')),
                ('memory_usage', models.FloatField(default=0.0)),
                ('memory_over_allocation', models.FloatField(default=1.0)),
                ('storage', models.PositiveIntegerField(help_text='Storage in MB')),
                ('storage_usage', models.FloatField(default=0.0)),
                ('storage_over_allocation', models.FloatField(default=1.0)),
                ('daemon_version', models.CharField(blank=True, max_length=50, null=True)),
                ('docker_version', models.CharField(blank=True, max_length=50, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daemon_port', models.PositiveIntegerField(default=8080)),
                ('daemon_sftp_port', models.PositiveIntegerField(default=2022)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='billing.usersubscription')),
            ],
        ),
    ]
