# Generated by Django 5.2.8 on 2025-11-30 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('nodes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('owner', 'name')},
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['ip_address'], name='nodes_node_ip_addr_38f753_idx'),
        ),
    ]
