# Generated by Django 5.2.8 on 2025-12-03 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_alter_node_unique_together_and_more'),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='servers.server'),
        ),
    ]
