# Generated by Django 5.2.8 on 2025-12-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_node_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='server',
        ),
    ]
