# Generated by Django 5.2.8 on 2025-12-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_remove_node_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='subscription',
        ),
    ]
