# Generated by Django 5.2.8 on 2025-12-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0005_remove_node_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='key',
            field=models.CharField(default='b427f7dcaad17ffd98334a4b0b5027ce36f2214e0fee4f4c66bbd7091d03caee', max_length=128),
        ),
    ]
