# Generated by Django 5.2.8 on 2025-12-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0006_node_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='last_heartbeat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='key',
            field=models.CharField(default='326801f56ad95921f17ee4926f16e71b8618774d040faeaee8c1b750e151147f', max_length=128),
        ),
    ]
