# Generated by Django 5.2.8 on 2025-12-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0007_node_is_online_node_last_heartbeat_alter_node_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='key',
            field=models.CharField(default='d197f29833d21324ca71452da4aa50d42c6425cfcc4ea60429bf988129b1c792', max_length=128),
        ),
    ]
