# Generated by Django 5.2.8 on 2025-12-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0008_alter_node_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='key',
            field=models.CharField(default='465206f8921d8f393c442a452fa85c3dc6a4f649467a48c617a005dd4bfcfcec', max_length=128),
        ),
    ]
