# Generated by Django 5.2.8 on 2025-12-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0009_alter_node_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='key',
            field=models.CharField(default='62e1fc1c250ca55038b03515fd9f8838a2e3108f8cd01e9d0b74d4230e70b3cb', max_length=128),
        ),
    ]
