# Generated by Django 5.2.8 on 2025-11-30 03:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('artifact_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('paper', 'PaperMC'), ('spigot', 'SpigotMC'), ('fabric', 'Fabric'), ('forge', 'Forge')], default='paper', max_length=20)),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='provisioning', max_length=20)),
                ('java_version', models.CharField(max_length=20)),
                ('mc_version', models.CharField(max_length=20)),
                ('size_in_mb', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cpu_cores', models.PositiveIntegerField(default=1)),
                ('memory_in_mb', models.PositiveIntegerField(default=512)),
                ('root_path', models.FileField(upload_to='artifacts/source_files/')),
                ('registry_path', models.CharField(blank=True, max_length=255, null=True)),
                ('dockerfile_path', models.FileField(blank=True, null=True, upload_to='artifacts/dockerfiles/')),
                ('logs_path', models.FileField(blank=True, null=True, upload_to='artifacts/logs/')),
                ('hash_value', models.CharField(max_length=128)),
                ('flags', models.JSONField(blank=True, null=True)),
                ('active_instances', models.PositiveIntegerField(default=0)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creation_date'],
                'indexes': [models.Index(fields=['owner'], name='artifacts_a_owner_i_42cad8_idx'), models.Index(fields=['type', 'status'], name='artifacts_a_type_a6725c_idx')],
            },
        ),
    ]
