# Generated by Django 5.2.8 on 2025-11-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='root_path',
            field=models.CharField(max_length=255),
        ),
    ]
