# Generated by Django 5.2.8 on 2025-11-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0002_alter_artifact_root_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='hash_value',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
