# Generated by Django 5.2.8 on 2025-11-30 21:44

import applications.artifacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0003_alter_artifact_hash_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='root_path',
        ),
        migrations.AddField(
            model_name='artifact',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=applications.artifacts.models.artifact_upload_path),
        ),
    ]
