# Generated by Django 5.2.8 on 2025-12-02 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0004_remove_artifact_root_path_artifact_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='description',
            field=models.TextField(max_length=128),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='size_in_mb',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='version',
            field=models.CharField(default='not builded', max_length=50),
        ),
    ]
