# Generated by Django 5.2.8 on 2025-12-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0005_alter_artifact_description_alter_artifact_size_in_mb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artifact',
            old_name='file',
            new_name='zip_file',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='dockerfile_path',
        ),
        migrations.AddField(
            model_name='artifact',
            name='dockerfile',
            field=models.TextField(blank=True),
        ),
    ]
