# Generated by Django 5.2.8 on 2025-12-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0006_rename_file_artifact_zip_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='logs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
