# Generated by Django 5.2.8 on 2025-12-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0007_artifact_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='hash_value',
        ),
        migrations.AlterField(
            model_name='artifact',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('not_builded', 'Not Builded'), ('ready', 'Ready'), ('error', 'Error')], default='not_builded', max_length=20),
        ),
    ]
