# Generated by Django 5.2.8 on 2025-12-03 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0008_remove_artifact_hash_value_alter_artifact_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='logs_path',
        ),
    ]
