# Generated by Django 5.2.8 on 2025-12-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0009_remove_artifact_logs_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='dockerfile',
        ),
        migrations.AddField(
            model_name='artifact',
            name='dockerfile_custom',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='dockerfile_name',
            field=models.CharField(choices=[('paper', 'paper'), ('purpur', 'purpur')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
