# Generated by Django 5.2.8 on 2025-12-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0010_remove_artifact_dockerfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='dockerfile_name',
            field=models.CharField(choices=[('paper', 'paper'), ('purpur', 'purpur')], default='paper', max_length=50),
        ),
    ]
