# Generated by Django 5.2.8 on 2025-12-03 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0011_alter_artifact_dockerfile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='flags',
        ),
    ]
