# Generated by Django 5.2.8 on 2025-12-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0012_remove_artifact_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='dockerfile_name',
            field=models.CharField(choices=[('paper', 'paper')], default='paper', max_length=50),
        ),
    ]
