# Generated by Django 5.2.8 on 2025-11-30 03:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifacts', '0001_initial'),
        ('nodes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('server_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='provisioning', max_length=20)),
                ('ip_address', models.CharField(max_length=45, validators=[django.core.validators.validate_ipv46_address])),
                ('port', models.PositiveIntegerField()),
                ('players_online', models.PositiveIntegerField(default=0)),
                ('max_players', models.PositiveIntegerField(default=20)),
                ('cpu_allocated', models.PositiveIntegerField(editable=False)),
                ('memory_allocated', models.PositiveIntegerField(editable=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.BigIntegerField(default=0)),
                ('temp_logs_path', models.CharField(blank=True, max_length=255, null=True)),
                ('docker_container_id', models.CharField(blank=True, max_length=64, null=True)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='artifacts.artifact')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='nodes.node')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_date'],
                'indexes': [models.Index(fields=['owner'], name='servers_ser_owner_i_2de82c_idx'), models.Index(fields=['status'], name='servers_ser_status_dfa09b_idx'), models.Index(fields=['node'], name='servers_ser_node_id_3dba32_idx')],
            },
        ),
    ]
