# Generated by Django 5.2.8 on 2025-12-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_alter_server_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='tps',
            field=models.FloatField(default=0),
        ),
    ]
