# Generated by Django 5.2.8 on 2025-12-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_server_tps'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='key',
            field=models.CharField(default='b37d50ad5fc4466ef510bec6c37a5d0d7c8e067dcb7fca29c1ba63304f46e1f5', max_length=128),
        ),
        migrations.AddField(
            model_name='server',
            name='last_heartbeat',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
